name: fake_store_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  bloc: ^9.0.0
  colorful_safe_area: ^1.0.0
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_launcher_icons: ^0.14.3
  gap: ^3.0.1
  get_it: ^8.0.3
  go_router: ^14.8.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  path_provider: ^2.1.5
  rename_app: ^1.6.2
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  sqflite: ^2.3.0+3

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: 3.0.0-0.0.dev
  freezed_annotation: ^2.4.4
  json_serializable: ^6.9.4
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"
